<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>intest</ToolCommandName>
    <PackageId>InTest.Cli</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RootNamespace>InTest.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="all" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="Scriban" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Rendering/Templates/*.scriban" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="InTest.Cli.Tests" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../assets/icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
